apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: exchange-api-template
objects:
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: exchange-api
    spec:
      replicas: 3
      template:
        spec:
          containers:
            - name: exchange-api
              image: ${IMAGE_REGISTRY}/exchange-api:v1.2.0
              env:
                - name: EXCHANGE_ENDPOINT
                  value: "${EXCHANGE_ENDPOINT}"
parameters:
  - name: IMAGE_REGISTRY
    required: true
  - name: EXCHANGE_ENDPOINT
    required: true